### ISSUE TITLE
help，can't repair json 

### ISSUE THREAD

**Issue by TinChi0818** [coderphonui/jsonautorepair#1]
help，can't repair json like this：
```
{
        "id": "1",
        "name": "zhangsan",
        "value": "true",
        "type": "5,
        "hits": [
            {
                "hitText": "hello,",
                "index": "2"
            }
        ],
        "reason": "xxxxxxxx"
    }```

**Comment by coderphonui** [comment]
The value you put is missing close quote at the line:

"type": "5

This was not handled yet. Thanks for reporting the issue. I am checking it out

**Comment by coderphonui** [comment]
This issue was fixed. I merged the PR to the main branch. Try it and let me know if it works for you. Thanks

**Comment by TinChi0818** [comment]
sorry, it doesn't work at all.
but remove the comma in the text:
"hitText": "hello," => "hitText": "hello", it works.

the exception stack：
```
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 8 column 39 path $.hits[0].
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:99)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:68)
	at com.google.gson.JsonParser.parseString(JsonParser.java:50)
	at com.app.llm.utils.JSONRepairer.attemptToFix(JSONRepairer.java:74)
	at com.app.llm.utils.JSONRepairer.repair(JSONRepairer.java:44)
	at com.app.llm.utils.JSONRepairer.main(JSONRepairer.java:31)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 8 column 39 path $.hits[0].
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1607)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:540)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:435)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:759)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 6 more

**Comment by coderphonui** [comment]
Should be good now. I missed that case. Just added to the test and fixed it. 
Ref: https://github.com/coderphonui/jsonautorepair/blob/main/src/test/java/com/cdpn/jsonautorepair/JSONAutoRepairerTest.java#L78

**Comment by TinChi0818** [comment]
It works，thank you very much.

**Comment by coderphonui** [comment]
You're welcome!
